### ISSUE TITLE
Search notes is very slow

### ISSUE THREAD

**Issue by ahmeed83** [marcjulianschwarz/obsidian-raycast#24] opened 2022-07-31 20:02 UTC
Hello, 

Thanks a lot for building this extension. 

But I'm noticing a weird behaviour (I don't know if I have to change anything from my side).

When I search for a note, it takes a very long time to show up. Sometimes it keeps loading without showing anything. 

https://user-images.githubusercontent.com/6630503/182043121-5225ff2c-5952-4068-97d4-008c4968c3af.mov

**Comment by marcjulianschwarz** [comment] 2022-07-31 21:39
This is definitely not expected behaviour. 

May I ask how many notes the vault contains?

Does it work for other vaults?

**Comment by marcjulianschwarz** [comment] 2022-07-31 21:46
If you dont mind you could clone this repository, run `npm install` and `npm run dev` to try out the newest version. I implemented better caching, maybe this will help with the performance issues.

**Comment by ahmeed83** [comment] 2022-08-02 13:07
Thanks for answering. I don't have many notes, like 20 or something. It does not work for the other vault as well. 

I will try cloning the project and will let you know

**Comment by briansport13** [comment] 2022-08-07 14:17
Hi, I can confirm that I'm having this problem as well. I've just started using Obsidian & I've tested it with only a couple of notes to check if it was an issue with having too many notes, but it wasn't. In my case, I never experienced a slow opening, just an infinite loading screen that I would have to circumvent by either closing & reopening the extension or pressing the Command + P & then pressing Enter selecting the option All on the search for opportunity. By doing that, it would load all my notes instantly. Currently, I use keyboard maestro macro to detect if the extension is not loading (It doesn't always happen sometimes. It would load instantly, but it's always random) & if it's not loading, then I would simulate the Command+P and then Enter Keystroke to load my notes (Very janky & not ideal at all).

**Comment by marcjulianschwarz** [comment] 2022-08-07 14:42
Hi @briansport13,

thank your for providing more context. Could you please make a copy of the vault available so I can test it and/or share the preferences of the extension?

If you can't share the vault, you could do me a favor by cloning this repo and trying to install it using `npm install` and `npm run dev` to see if the issue is still there.

**Comment by briansport13** [comment] 2022-08-07 15:44
Hi, I'm not sure how you would share the vault. Maybe you could clarify it
to me, but here's the extension preference screenshot. I'll give it a shot,
but it's my first time using GitHub, so I'll give it my best shot, but I
might not be able to get it running correctly. Regarding the preferences,
I've tried to tinker with preferences to see if anything would change but
so far no luck, so I don't think it has anything to do with the preference

Pada tanggal Min, 7 Agu 2022 pukul 21.43 Marc Julian Schwarz <
***@***.***> menulis:

**Comment by marcjulianschwarz** [comment] 2022-08-07 16:26
It would help a lot if you could zip the folder of yout vault (the folder "Main") and maybe send it to my mail which you can find [here](https://www.marc-julian.de/impressum.html).

And you can try to remove the path you set in the second picture. The extension should detect your vault automatically if it was opened with Obsidian before.

**Comment by marcjulianschwarz** [comment] 2022-08-15 11:12
Hi @ahmeed83, @briansport13,

the new version has been released. You might want to try if the issue is still there.
Updated in Raycast should install automatically but you can always search for the command `Check for Extensions Updates` to manually install them.

**Closed by marcjulianschwarz** 2022-08-15 11:12 UTC
Labels: bug
