### ISSUE TITLE
JS heap out of memory when using detail view

### ISSUE THREAD

**Issue by Dzar34** [marcjulianschwarz/obsidian-raycast#19] opened 2022-06-10 12:40 UTC
Hello, thanks for building this! Unfortunately, every time I attempt to search my vault, I can see a list of my notes for a split second, then I get an error. Message copied below. Thanks for any help!

Error: Worker terminated due to reaching memory limit: JS heap out of memory

__node_internal_captureLargerStackTrace:errors:464:5
NodeError:errors:371:5
Worker.[kOnExit]:worker:279:26
Worker.<computed>.onexit:worker:201:20

**Comment by marcjulianschwarz** [comment] 2022-06-10 14:02
Hello @Dzar34,

looks like you have too many notes for the Detail View.
Try turning off the Detail View in the extensions preferences.

If that doesn’t help I will take a look at it. And I will try to find a solution for it to work with any amount of notes.

**Comment by Dzar34** [comment] 2022-06-18 22:19
Thanks for responding! I did turn off detail view, but I am still getting the same error. I have 10,650 notes 😳 I may just be an outlier!

**Comment by marcjulianschwarz** [comment] 2022-06-19 11:26
I was able to reproduce the error by creating a vault with 10.000 notes each with 100 words. It looks like the notes load just fine (independent of detail view state).

Logging the current memory usage reveals that the extension uses about 0.06 GB which should not be enough to reach the memory limit of node. 
Another thing that I noticed was that everything worked as long as I was *slowly* going through the search results. The second I held down an arrow key (thus going through the results very fast) it reached the memory limit. The same thing happens when using the search, going through different queries fast will fill result in an error but it won't crash when I search *slowly*.

Help from someone with more experience is greatly appreciated as I currently don't know how to fix this.

**Comment by marcjulianschwarz** [comment] 2022-06-19 13:59
Found a way to get this fixed. Seems like Raycast can't handle rendering for more than 1k-3k list items. With the newest commit only 2000 items will be rendered and they change based on the search query.

**Comment by marcjulianschwarz** [comment] 2022-06-22 06:37
This has been fixed with version 1.6.0 which has now been released.

**Closed by marcjulianschwarz** 2022-06-22 06:37 UTC
Labels: bug, done

**Comment by Dzar34** [comment] 2022-06-22 21:10
It works great!! Thanks so much for creating this and working on a fix. I love it!
